server:
  port: 8060

spring:
  application:
    name: ms-notificacao
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: local-vh

user:
  queue:
    name-create: create-user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka